services:
  http-proxy:
    image: codekitchen/dinghy-http-proxy
    container_name: http-proxy
    restart: always
    environment:
      - CONTAINER_NAME=http-proxy
    ports:
      - "80:80"
      - "443:443"
      - "19322:19322/udp"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.dinghy/certs:/etc/nginx/certs:ro
